const spots=[
{name:'El Nido',location:'Palawan',category:'Beach',image:'https://images.unsplash.com/photo-1544550285-f813152fb2fd?auto=format&fit=crop&w=800&q=85',description:'Turquoise lagoons, limestone cliffs, at white sand beaches na parang postcard.',budget:'₱3,500 – ₱6,000',activities:'Island hopping, snorkeling, kayaking',fee:'₱200 environmental fee'},
{name:'Kawasan Falls',location:'Badian, Cebu',category:'Waterfall',image:'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=800&q=85',description:'Makulay na blue waters at refreshing waterfalls para sa isang exciting adventure.',budget:'₱1,500 – ₱3,000',activities:'Canyoneering, swimming, trekking',fee:'₱40 entrance fee'},
{name:'Mt. Pulag',location:'Benguet',category:'Mountain',image:'https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=800&q=85',description:'Saksihan ang sikat na sea of clouds at golden sunrise sa pinakamataas na bundok ng Luzon.',budget:'₱2,000 – ₱4,000',activities:'Hiking, camping, sightseeing',fee:'₱175 registration fee'},
{name:'Intramuros',location:'Manila',category:'Historical',image:'https://images.unsplash.com/photo-1552457499-6f5b1a2a4e0e?auto=format&fit=crop&w=800&q=85',description:'Maglakad sa lumang Maynila at balikan ang kasaysayan sa loob ng napapaderang lungsod.',budget:'₱800 – ₱1,500',activities:'Walking tour, sightseeing, food trip',fee:'₱75 museum entrance'},
{name:'Baguio Botanical Garden',location:'Baguio City',category:'Park',image:'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=800&q=85',description:'Tahimik at malamig na garden na puno ng halaman, flowers, at local culture.',budget:'₱1,000 – ₱2,500',activities:'Nature walk, photography, sightseeing',fee:'₱100 entrance fee'},
{name:'Nacpan Beach',location:'El Nido, Palawan',category:'Beach',image:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=85',description:'Four-kilometer stretch of powdery sand at malinaw na dagat para sa slow beach day.',budget:'₱2,500 – ₱5,000',activities:'Swimming, sunbathing, sunset watching',fee:'₱50 entrance fee'}
];
let activeCategory='All';
const grid=document.getElementById('spotGrid'), search=document.getElementById('searchInput'), modal=document.getElementById('spotModal');
function renderSpots(){const query=search.value.toLowerCase().trim();const results=spots.filter(s=>(activeCategory==='All'||s.category===activeCategory)&&`${s.name} ${s.location} ${s.category}`.toLowerCase().includes(query));grid.innerHTML=results.length?results.map(s=>`<article class="spot-card"><div class="spot-image" style="background-image:url('${s.image}')"><span class="spot-badge">${s.category}</span><button class="favorite" aria-label="favorite">♡</button></div><div class="spot-body"><h3>${s.name}</h3><div class="location">📍 <b>${s.location}</b></div><p>${s.description}</p><div class="spot-footer"><div class="price">Budget mula sa<strong>${s.budget.split(' – ')[0]}</strong></div><button class="details" data-name="${s.name}">View details →</button></div></div></article>`).join(''):'<div class="empty">😔 Walang nahanap. Subukan ang ibang search o category.</div>';document.querySelectorAll('.details').forEach(btn=>btn.onclick=()=>openModal(spots.find(s=>s.name===btn.dataset.name)));document.querySelectorAll('.favorite').forEach(btn=>btn.onclick=()=>{btn.textContent=btn.textContent==='♡'?'♥':'♡';btn.style.color=btn.textContent==='♥'?'#e75c5c':''});}
function openModal(spot){if(!spot)return;document.getElementById('modalImage').style.backgroundImage=`url('${spot.image}')`;document.getElementById('modalTitle').textContent=spot.name;document.getElementById('modalLocation').textContent=`📍 ${spot.location} · ${spot.category}`;document.getElementById('modalDescription').textContent=spot.description;document.getElementById('modalInfo').innerHTML=`<div class="info-item"><b>Estimated budget</b>${spot.budget}</div><div class="info-item"><b>Entrance fee</b>${spot.fee}</div><div class="info-item"><b>Activities</b>${spot.activities}</div><div class="info-item"><b>Best for</b>Friends & family</div>`;modal.classList.add('show');}
function closeModal(){modal.classList.remove('show')}
search.oninput=renderSpots;document.getElementById('searchButton').onclick=renderSpots;document.getElementById('closeModal').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};document.querySelectorAll('.category').forEach(btn=>btn.onclick=()=>{document.querySelector('.category.active').classList.remove('active');btn.classList.add('active');activeCategory=btn.dataset.category;renderSpots()});renderSpots();
