const spots=[
{name:'El Nido',location:'Palawan',category:'Beach',image:'https://images.unsplash.com/photo-1544550285-f813152fb2fd?auto=format&fit=crop&w=800&q=85',description:'Turquoise lagoons, limestone cliffs, and white sand beaches.',budget:'₱3,500 – ₱6,000',activities:'Island hopping, snorkeling, kayaking',flight:4800},
{name:'Kawasan Falls',location:'Badian, Cebu',category:'Waterfall',image:'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=800&q=85',description:'Blue waters and exciting canyoneering adventure.',budget:'₱1,500 – ₱3,000',activities:'Canyoneering, swimming, trekking',flight:3200},
{name:'Mt. Pulag',location:'Benguet',category:'Mountain',image:'https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=800&q=85',description:'Sea of clouds and golden sunrise for hikers.',budget:'₱2,000 – ₱4,000',activities:'Hiking, camping, sightseeing',flight:3600},
{name:'Intramuros',location:'Manila',category:'Historical',image:'https://images.unsplash.com/photo-1552457499-6f5b1a2a4e0e?auto=format&fit=crop&w=800&q=85',description:'Explore old Manila inside the historic walled city.',budget:'₱800 – ₱1,500',activities:'Walking tour, sightseeing, food trip',flight:0},
{name:'Baguio Botanical Garden',location:'Baguio City',category:'Park',image:'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=800&q=85',description:'Cool weather, flowers, greenery, and local culture.',budget:'₱1,000 – ₱2,500',activities:'Nature walk, photography, sightseeing',flight:3500},
{name:'Nacpan Beach',location:'El Nido, Palawan',category:'Beach',image:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=85',description:'Powdery sand and clear water for a peaceful beach day.',budget:'₱2,500 – ₱5,000',activities:'Swimming, sunset watching',flight:4800}
];
const $=id=>document.getElementById(id),money=n=>'₱'+Number(n).toLocaleString('en-PH');let authMode='login',activeCategory='All',selected=spots[0];
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2800)}
function setAuthMode(mode){authMode=mode;$('emailField').classList.toggle('hidden',mode==='login');$('email').required=mode==='register';$('authTitle').textContent=mode==='login'?'Welcome back!':'Create your account';$('authText').textContent=mode==='login'?'Mag-login muna para makapasok sa travel dashboard.':'Gumawa ng account gamit ang username at password.';$('authButton').textContent=mode==='login'?'Log in':'Register';$('switchAuth').textContent=mode==='login'?'Wala pang account? Register':'May account na? Log in';$('authMessage').textContent=''}
function showApp(){const user=JSON.parse(localStorage.getItem('lakbayUser')||'null');if(!user)return;$('authView').classList.add('hidden');$('appView').classList.remove('hidden');$('welcome').textContent='Hi, '+user.username+'!'}
if(localStorage.getItem('lakbayUser'))showApp();
$('switchAuth').onclick=()=>setAuthMode(authMode==='login'?'register':'login');
$('authForm').onsubmit=e=>{e.preventDefault();const username=$('username').value.trim(),password=$('password').value,email=$('email').value.trim().toLowerCase();if(username.length<3){$('authMessage').textContent='Username must be at least 3 characters.';return}if(password.length<6){$('authMessage').textContent='Password must be at least 6 characters.';return}if(authMode==='register'){localStorage.setItem('lakbayAccount',JSON.stringify({username,password,email}));$('authMessage').style.color='green';$('authMessage').textContent='Registered successfully. Mag-login na ngayon.';setAuthMode('login');$('username').value=username;$('password').value='';return}const account=JSON.parse(localStorage.getItem('lakbayAccount')||'null');if(!account||account.username.toLowerCase()!==username.toLowerCase()||account.password!==password){$('authMessage').textContent='Mali ang username o password.';return}localStorage.setItem('lakbayUser',JSON.stringify({username:account.username}));showApp()};
$('logout').onclick=()=>{localStorage.removeItem('lakbayUser');location.reload()};
$('categories').innerHTML=['All','Beach','Waterfall','Mountain','Park','Historical'].map(c=>`<button class="category ${c==='All'?'active':''}" data-category="${c}">${c}</button>`).join('');
function renderSpots(){const query=$('search').value.trim().toLowerCase();const result=spots.filter(s=>(activeCategory==='All'||s.category===activeCategory)&&`${s.name} ${s.location} ${s.category}`.toLowerCase().includes(query));$('spotGrid').innerHTML=result.length?result.map(s=>`<article class="spot-card"><div class="spot-image" style="background-image:url('${s.image}')"><span class="badge">${s.category}</span><button class="favorite">♡</button></div><div class="spot-body"><h3>${s.name}</h3><div class="location">📍 ${s.location}</div><p>${s.description}</p><div class="spot-footer"><span>Budget mula sa<strong>${s.budget.split(' – ')[0]}</strong></span><button class="details" data-name="${s.name}">View details →</button></div></div></article>`).join(''):'<p class="muted">Walang nahanap na destination.</p>';document.querySelectorAll('.details').forEach(button=>button.onclick=()=>openDetails(spots.find(s=>s.name===button.dataset.name)));document.querySelectorAll('.favorite').forEach(button=>button.onclick=()=>{button.textContent=button.textContent==='♡'?'♥':'♡';button.style.color=button.textContent==='♥'?'#e75c5c':''})}
function openDetails(spot){selected=spot;$('modalTitle').textContent=spot.name;$('modalLocation').textContent='📍 '+spot.location+' · '+spot.category;$('modalDescription').textContent=spot.description;$('modalInfo').innerHTML=`<div><b>Estimated budget</b>${spot.budget}</div><div><b>Activities</b>${spot.activities}</div><div><b>Flight estimate</b>${spot.flight?money(spot.flight):'Land travel'}</div><div><b>Access</b>Open destination details</div>`;$('spotModal').classList.remove('hidden')}
$('closeModal').onclick=()=>$('spotModal').classList.add('hidden');$('spotModal').onclick=e=>{if(e.target===$('spotModal'))$('spotModal').classList.add('hidden')};$('bookSpot').onclick=()=>{$('destination').value=selected.name;updatePrice();$('spotModal').classList.add('hidden');$('planner').scrollIntoView({behavior:'smooth'})};document.querySelectorAll('.category').forEach(button=>button.onclick=()=>{document.querySelector('.category.active').classList.remove('active');button.classList.add('active');activeCategory=button.dataset.category;renderSpots()});$('search').oninput=renderSpots;$('searchButton').onclick=()=>{renderSpots();$('spots').scrollIntoView({behavior:'smooth'})};
$('destination').innerHTML=spots.map(s=>`<option value="${s.name}">${s.name} — ${s.location}</option>`).join('');function updatePrice(){const spot=spots.find(s=>s.name===$('destination').value);if(!spot)return;let total=spot.flight||0;total+=({MNL:0,CEB:500,DVO:900}[$('airport').value]||0);total*=Number($('tripType').value);total*=Math.max(1,Number($('travelers').value));$('flightPrice').textContent=total?money(total):'₱0 (land travel)'}['destination','airport','tripType'].forEach(id=>$(id).onchange=updatePrice);$('travelers').oninput=updatePrice;$('travelDate').min=new Date().toISOString().slice(0,10);$('bookingForm').onsubmit=e=>{e.preventDefault();const code='LPH-'+Math.random().toString(36).slice(2,8).toUpperCase();toast('Booking saved: '+code)};updatePrice();renderSpots();
