const spots=[
{name:'El Nido',location:'Palawan',category:'Beach',image:'https://images.unsplash.com/photo-1544550285-f813152fb2fd?auto=format&fit=crop&w=1000&q=90',description:'Turquoise lagoons, limestone cliffs, and white-sand beaches in El Nido.',budget:'₱3,500 – ₱6,000',activities:'Island hopping, snorkeling, kayaking',flight:4800},
{name:'Kawasan Falls',location:'Badian, Cebu',category:'Waterfall',image:'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1000&q=90',description:'Blue waters and exciting canyoneering adventure at the famous Kawasan Falls.',budget:'₱1,500 – ₱3,000',activities:'Canyoneering, swimming, trekking',flight:3200},
{name:'Mt. Pulag',location:'Benguet',category:'Mountain',image:'https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1000&q=90',description:'Sea of clouds and golden sunrise for hikers and campers.',budget:'₱2,000 – ₱4,000',activities:'Hiking, camping, sightseeing',flight:3600},
{name:'Intramuros',location:'Manila',category:'Historical',image:'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?auto=format&fit=crop&w=1000&q=90',description:'Explore old Manila inside the historic walled city.',budget:'₱800 – ₱1,500',activities:'Walking tour, sightseeing, food trip',flight:0},
{name:'Baguio Botanical Garden',location:'Baguio City',category:'Park',image:'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=1000&q=90',description:'Cool weather, flowers, greenery, and local culture.',budget:'₱1,000 – ₱2,500',activities:'Nature walk, photography, sightseeing',flight:3500},
{name:'Nacpan Beach',location:'El Nido, Palawan',category:'Beach',image:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=90',description:'Powdery sand and clear water for a peaceful beach day.',budget:'₱2,500 – ₱5,000',activities:'Swimming, sunset watching',flight:4800},
{name:'Chocolate Hills',location:'Carmen, Bohol',category:'Mountain',image:'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1000&q=90',description:'A breathtaking landscape of cone-shaped hills in Bohol.',budget:'₱1,500 – ₱3,500',activities:'Sightseeing, photography, countryside tour',flight:3000},
{name:'Boracay White Beach',location:'Malay, Aklan',category:'Beach',image:'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?auto=format&fit=crop&w=1000&q=90',description:'White sand, clear water, and unforgettable sunsets.',budget:'₱4,000 – ₱8,000',activities:'Swimming, diving, sailing, sunset cruise',flight:4200},
{name:'Mayon Volcano',location:'Albay, Bicol',category:'Mountain',image:'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1000&q=90',description:'See the perfectly shaped Mayon Volcano and explore Albay.',budget:'₱2,000 – ₱4,000',activities:'Sightseeing, ATV ride, photography',flight:3800},
{name:'Puerto Princesa Underground River',location:'Palawan',category:'Waterfall',image:'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1000&q=90',description:'A UNESCO site with a spectacular underground river cave.',budget:'₱3,000 – ₱6,000',activities:'Boat tour, caving, wildlife watching',flight:4800},
{name:'Rizal Park',location:'Manila',category:'Park',image:'https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1000&q=90',description:'A historic urban park and relaxing green space in Manila.',budget:'₱500 – ₱1,200',activities:'Walking, sightseeing, picnic, photography',flight:0},
{name:'Vigan Heritage Village',location:'Vigan, Ilocos Sur',category:'Historical',image:'https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1000&q=90',description:'Cobblestone streets and Spanish-era architecture.',budget:'₱1,500 – ₱3,000',activities:'Heritage walk, kalesa ride, food trip',flight:4200}
];
const $=id=>document.getElementById(id),money=n=>`₱${Number(n).toLocaleString('en-PH')}`;let authMode='login',activeCategory='All',selected=spots[0];
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2800)}
function setAuthMode(m){authMode=m;$('emailField').classList.toggle('hidden',m==='login');$('email').required=m==='register';$('authTitle').textContent=m==='login'?'Welcome back!':'Create your account';$('authText').textContent=m==='login'?'Mag-login muna para makapasok sa travel dashboard.':'Gumawa ng account gamit ang username at password.';$('authButton').textContent=m==='login'?'Log in':'Register';$('switchAuth').textContent=m==='login'?'Wala pang account? Register':'May account na? Log in';$('authMessage').textContent=''}
function showApp(){const u=JSON.parse(localStorage.getItem('lakbayUser')||'null');if(!u)return;$('authView').classList.add('hidden');$('appView').classList.remove('hidden');$('welcome').textContent=`Hi, ${u.username}!`}
if(localStorage.getItem('lakbayUser'))showApp();$('switchAuth').onclick=()=>setAuthMode(authMode==='login'?'register':'login');
$('authForm').onsubmit=e=>{e.preventDefault();const username=$('username').value.trim(),password=$('password').value,email=$('email').value.trim().toLowerCase();if(username.length<3)return $('authMessage').textContent='Username must be at least 3 characters.';if(password.length<6)return $('authMessage').textContent='Password must be at least 6 characters.';if(authMode==='register'){localStorage.setItem('lakbayAccount',JSON.stringify({username,password,email}));$('authMessage').style.color='green';$('authMessage').textContent='Registered successfully. Mag-login na ngayon.';setAuthMode('login');$('username').value=username;$('password').value='';return}const a=JSON.parse(localStorage.getItem('lakbayAccount')||'null');if(!a||a.username.toLowerCase()!==username.toLowerCase()||a.password!==password)return $('authMessage').textContent='Mali ang username o password.';localStorage.setItem('lakbayUser',JSON.stringify({username:a.username}));showApp()};$('logout').onclick=()=>{localStorage.removeItem('lakbayUser');location.reload()};
$('categories').innerHTML=['All','Beach','Waterfall','Mountain','Park','Historical'].map(c=>`<button class="category ${c==='All'?'active':''}" data-category="${c}">${c}</button>`).join('');
function renderSpots(){const q=$('search').value.trim().toLowerCase(),list=spots.filter(s=>(activeCategory==='All'||s.category===activeCategory)&&`${s.name} ${s.location} ${s.category}`.toLowerCase().includes(q));$('spotGrid').innerHTML=list.length?list.map(s=>`<article class="spot-card"><div class="spot-image" style="background-image:url('${s.image}')"><span class="badge">${s.category}</span><button class="favorite" type="button">♡</button></div><div class="spot-body"><h3>${s.name}</h3><div class="location">📍 ${s.location}</div><p>${s.description}</p><div class="spot-footer"><span>Budget mula sa<strong>${s.budget.split(' – ')[0]}</strong></span><button class="details" type="button" data-name="${s.name}">View details →</button></div></div></article>`).join(''):'<p class="muted">Walang nahanap na destination.</p>';document.querySelectorAll('.details').forEach(b=>b.onclick=()=>openDetails(spots.find(s=>s.name===b.dataset.name)));document.querySelectorAll('.favorite').forEach(b=>b.onclick=()=>{b.textContent=b.textContent==='♡'?'♥':'♡';b.style.color=b.textContent==='♥'?'#e75c5c':''})}
function openDetails(s){if(!s)return;selected=s;$('modalImage').style.backgroundImage=`url('${s.image}')`;$('modalTitle').textContent=s.name;$('modalLocation').textContent=`📍 ${s.location} · ${s.category}`;$('modalDescription').textContent=s.description;$('modalInfo').innerHTML=`<div><b>Estimated budget</b>${s.budget}</div><div><b>Activities</b>${s.activities}</div><div><b>Flight estimate</b>${s.flight?money(s.flight):'Land travel'}</div>`;$('googleMapsButton').href=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${s.name}, ${s.location}, Philippines`)}`;$('spotModal').classList.remove('hidden')}
$('closeModal').onclick=()=>$('spotModal').classList.add('hidden');$('spotModal').onclick=e=>{if(e.target===$('spotModal'))$('spotModal').classList.add('hidden')};$('bookSpot').onclick=()=>{$('destination').value=selected.name;updatePrice();$('spotModal').classList.add('hidden');$('planner').scrollIntoView({behavior:'smooth'})};document.querySelectorAll('.category').forEach(b=>b.onclick=()=>{document.querySelector('.category.active').classList.remove('active');b.classList.add('active');activeCategory=b.dataset.category;renderSpots()});$('search').oninput=renderSpots;$('searchButton').onclick=()=>{renderSpots();$('spots').scrollIntoView({behavior:'smooth'})};
$('destination').innerHTML=spots.map(s=>`<option value="${s.name}">${s.name} — ${s.location}</option>`).join('');function updatePrice(){const s=spots.find(x=>x.name===$('destination').value);if(!s)return;let total=(s.flight||0)+({MNL:0,CEB:500,DVO:900}[$('airport').value]||0);total*=Number($('tripType').value);total*=Math.max(1,Number($('travelers').value));$('flightPrice').textContent=total?money(total):'₱0 (land travel)'}['destination','airport','tripType'].forEach(id=>$(id).onchange=updatePrice);$('travelers').oninput=updatePrice;$('travelDate').min=new Date().toISOString().slice(0,10);
function getBookings(){return JSON.parse(localStorage.getItem('lakbayBookings')||'[]')}
function saveBookings(items){localStorage.setItem('lakbayBookings',JSON.stringify(items))}
function renderBookings(){const list=getBookings();$('bookingList').innerHTML=list.length?list.map(b=>`<div class="booking-row"><div><b>${b.destination}</b><small>${b.date} · ${b.travelers} traveler(s) · ${b.trip} · ${b.price}</small><small>Reference: ${b.code} · User: ${b.username}</small></div><button class="delete-booking" data-code="${b.code}">Delete</button></div>`).join(''):'<div class="empty-bookings">Wala pang booking. Gumawa muna ng booking sa Trip Planner.</div>';document.querySelectorAll('.delete-booking').forEach(b=>b.onclick=()=>{saveBookings(getBookings().filter(x=>x.code!==b.dataset.code));renderBookings();toast('Booking deleted.')})}
$('bookingForm').onsubmit=e=>{e.preventDefault();const u=JSON.parse(localStorage.getItem('lakbayUser')||'null');const code='LPH-'+Math.random().toString(36).slice(2,8).toUpperCase();const booking={code,username:u.username,destination:$('destination').value,date:$('travelDate').value,travelers:$('travelers').value,trip:Number($('tripType').value)===2?'Round trip':'One way',price:$('flightPrice').textContent};saveBookings([...getBookings(),booking]);toast(`Booking saved: ${code}`);e.target.reset();updatePrice()};
$('databaseButton').onclick=()=>{$('bookingModal').classList.remove('hidden');renderBookings()};$('closeBookings').onclick=()=>$('bookingModal').classList.add('hidden');$('bookingModal').onclick=e=>{if(e.target===$('bookingModal'))$('bookingModal').classList.add('hidden')};$('clearBookings').onclick=()=>{if(confirm('Burahin lahat ng bookings?')){saveBookings([]);renderBookings();toast('All bookings cleared.')}};
document.querySelectorAll('.feature').forEach(feature=>feature.onclick=()=>{const type=feature.dataset.feature;if(type==='bookings'){$('databaseButton').click();return}if(type==='activities'){activeCategory='All';$('search').value='';renderSpots();$('spots').scrollIntoView({behavior:'smooth'});toast('Showing destinations with activities.')}if(type==='budget'){activeCategory='All';$('spots').scrollIntoView({behavior:'smooth'});toast('Budget guides are shown on every destination card.')}if(type==='favorites'){toast('Tap the heart icon on a destination to save it.')}});
updatePrice();renderSpots();
